CREATE TABLE sync_roots (id INTEGER PRIMARY KEY AUTOINCREMENT, local_path TEXT NOT NULL, canonical_path TEXT NOT NULL UNIQUE, remote_path TEXT NOT NULL, remote_docid TEXT, enabled INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE files (id INTEGER PRIMARY KEY AUTOINCREMENT, sync_root_id INTEGER NOT NULL, local_path TEXT NOT NULL, canonical_path TEXT NOT NULL, remote_path TEXT NOT NULL, remote_docid TEXT, size INTEGER NOT NULL DEFAULT 0, mod_time INTEGER NOT NULL DEFAULT 0, is_dir INTEGER NOT NULL DEFAULT 0, etag TEXT, sync_status TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, UNIQUE(sync_root_id,canonical_path), FOREIGN KEY(sync_root_id) REFERENCES sync_roots(id) ON DELETE CASCADE);
CREATE TABLE tasks (id INTEGER PRIMARY KEY AUTOINCREMENT, operation TEXT NOT NULL CHECK(operation IN ('upload','download','mkdir','remove','rename')), local_path TEXT, canonical_path TEXT NOT NULL, remote_docid TEXT, destination TEXT, status TEXT NOT NULL CHECK(status IN ('pending','running','retry_wait','succeeded','failed')), attempts INTEGER NOT NULL DEFAULT 0, next_retry_at INTEGER, last_error TEXT, claimed_at INTEGER, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX idx_tasks_ready ON tasks(status,next_retry_at,created_at);
CREATE INDEX idx_tasks_canonical_path ON tasks(canonical_path,status);
CREATE UNIQUE INDEX idx_tasks_one_running_per_path ON tasks(canonical_path) WHERE status='running';
CREATE UNIQUE INDEX idx_tasks_active_dedup ON tasks(operation,canonical_path,COALESCE(destination,'')) WHERE status IN ('pending','running','retry_wait');
CREATE TABLE conflicts (id INTEGER PRIMARY KEY AUTOINCREMENT, local_path TEXT NOT NULL, remote_path TEXT NOT NULL, local_etag TEXT, remote_etag TEXT, resolution TEXT NOT NULL DEFAULT 'unresolved', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at INTEGER NOT NULL);
